services:
  service1:
    container_name: RollerCoasterService_NodeA
    build:
      context: .
      dockerfile: DockerFile.local
      args:
        - PORT=${PORT}
    environment:
      - ENV_TYPE=${ENV_TYPE}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - DATABASE=${DATABASE}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - custom_network

  service2:
    container_name: RollerCoasterService_NodeB
    build:
      context: .
      dockerfile: DockerFile.local
      args:
        - PORT=${PORT2}
    environment:
      - ENV_TYPE=${ENV_TYPE}
      - PORT=${PORT2}
      - REDIS_URL=${REDIS_URL}
      - DATABASE=${DATABASE}
    ports:
      - "${PORT2}:${PORT2}"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
